In [3]:
import pandas as pd

In [4]:
df = pd.read_excel('/content/BreakThroughTech_training_data_1.xlsx')
df

,brand,sub_product_name,country,pillar,media_type,profession,specialty,campaign_start_date,campaign_end_date,unique_reach,...,post_avg_NRx,pre_NRx_avg,npi_specialty,region,NRx_lift,NRx_lift_pct,cpe,total_spend,actual_spend_per_engagement,spend_per_NRx_lift
0,ABBVIE,BRAND ALERT,usa,search,SPONSORED_VIDEOS,8,undefined,2024-07-31 10:48:34.000000 UTC,2099-12-31 23:59:59.999999 UTC,9270,...,72.8343,47.4714,Neurology,Southeast,146.77,15.5000,39.0,1.343553e+08,30198.99,915440.73
1,ABBVIE,BRAND ALERT,usa,search,EDITORIAL_VIDEOS,8,undefined,2024-08-19 17:16:44.000000 UTC,2099-12-31 23:59:59.999999 UTC,1959,...,54.1279,62.6833,Cardiology,Southwest,112.05,12.2398,39.0,1.066785e+07,9055.90,95202.91
2,ABBVIE,BRAND ALERT,usa,search,SPONSORED_VIDEOS,psychologist,urology,2023-11-16 15:54:10.000000 UTC,2099-12-31 23:59:59.999999 UTC,2860,...,42.1019,66.2213,Cardiology,Mid-Atlantic,78.27,10.8516,39.0,5.910300e+07,34705.23,755161.42
3,ABBVIE,BRAND ALERT,zaf,search,SPONSORED_VIDEOS,8,undefined,2024-11-22 10:27:31.000000 UTC,2099-12-31 23:59:59.999999 UTC,7390,...,49.5424,55.8293,Neurology,Northeast,121.87,11.9201,39.0,1.244877e+08,112455.05,1021479.17
4,ABBVIE,EMAIL ALERT,NaN,NaN,NaN,NaN,NaN,2023-11-16 17:38:18.000000 UTC,2099-12-31 23:59:59.999999 UTC,77570,...,46.8907,39.3346,Endocrinology,Southwest,221.51,35.1116,3.0,8.924099e+08,7691.40,4028833.69
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
412,VIIV,EMAIL ALERT,NaN,NaN,NaN,NaN,NaN,2023-11-16 17:38:18.000000 UTC,2099-12-31 23:59:59.999999 UTC,38093,...,29.4993,18.0478,Internal Medicine,Northeast,139.32,37.9733,3.0,1.152618e+09,42555.60,8273271.98
413,VIIV,EMAIL ALERT,usa,search,EDITORIAL_VIDEOS,8,undefined,2023-05-02 13:53:22.000000 UTC,2099-12-31 23:59:59.999999 UTC,2569,...,53.2030,14.8198,Endocrinology,Pacific,99.14,25.9993,3.0,5.743438e+07,33353.30,579323.13
414,VIIV,EMAIL ALERT,usa,search,SPONSORED_VIDEOS,8,undefined,2024-07-31 10:48:34.000000 UTC,2099-12-31 23:59:59.999999 UTC,53210,...,37.6089,20.3695,Cardiology,Mid-Atlantic,154.35,26.2646,3.0,7.296974e+08,13539.74,4727549.06
415,VIIV,EMAIL ALERT,vgb,search,EDITORIAL_VIDEOS,8,undefined,2024-03-04 14:27:38.000000 UTC,2099-12-31 23:59:59.999999 UTC,1185,...,35.8581,24.1554,Endocrinology,West,105.21,17.4675,3.0,2.686829e+06,2520.48,25537.41
416,VIIV HEALTHCARE,EMAIL ALERT,NaN,NaN,NaN,NaN,NaN,2025-11-12 16:08:22.000000 UTC,2099-12-31 23:59:59.999999 UTC,5863,...,60.2757,44.0068,Dermatology,Northeast,361.52,33.6531,3.0,1.955250e+08,15412.66,540836.77

In [5]:
df.columns

Index(['brand', 'sub_product_name', 'country', 'pillar', 'media_type',
       'profession', 'specialty', 'campaign_start_date', 'campaign_end_date',
       'unique_reach', 'unique_engaged_hcps', 'total_engagements',
       'total_budget_spent', 'engagement_rate', 'engagement_frequency',
       'pre_NRx', 'post_NRx', 'pre_avg_NRx', 'post_avg_NRx', 'pre_NRx_avg',
       'npi_specialty', 'region', 'NRx_lift', 'NRx_lift_pct', 'cpe',
       'total_spend', 'actual_spend_per_engagement', 'spend_per_NRx_lift'],
      dtype='object')

In [10]:
subdf = df[['engagement_frequency', 'pre_NRx', 'post_NRx', 'pre_avg_NRx']]
subdf

     engagement_frequency  pre_NRx  post_NRx  pre_avg_NRx
0                    4.16   946.88   1093.64      63.0600
1                    3.10   915.49   1027.54      48.2253
2                    4.23   721.23    799.50      37.9804
3                    1.22  1022.39   1144.26      44.2658
4                    4.42   630.86    852.37      34.7051
..                    ...      ...       ...          ...
412                  1.41   366.89    506.20      21.3805
413                  2.52   381.32    480.46      42.2248
414                  3.96   587.67    742.02      29.7858
415                  1.96   602.33    707.54      30.5260
416                  3.94  1074.26   1435.79      45.0986

[417 rows x 4 columns]

In [11]:
subdf.describe()

       engagement_frequency      pre_NRx     post_NRx  pre_avg_NRx
count            417.000000   417.000000   417.000000   417.000000
mean               2.921367  1331.050791  1610.637290    88.827892
std                0.928341  1077.080943  1310.728418    85.163738
min                1.200000    35.080000    41.910000     2.225100
25%                2.190000   541.090000   631.510000    30.442200
50%                2.960000   972.620000  1167.580000    60.946500
75%                3.690000  1988.510000  2351.160000   125.189200
max                4.500000  3975.730000  5138.220000   487.412100

In [12]:
# All columns are numeric with no null values. No changes need to be made other than normalization